language: "ru-RU" #en-EN, ru-RU

database:
  type: "SQLITE" #MYSQL, SQLITE
  connection: "database.db"
  #user:
  #password:
  synchronize-interval-seconds: 120
registration-task-interval-seconds: 5

version: 1